/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdf90",
        "on-error": "#ffffff",
        "outline-variant": "#e0bfbf",
        "on-primary": "#ffffff",
        "on-surface-variant": "#584141",
        "on-secondary-fixed": "#241a00",
        "tertiary-container": "#413d33",
        "on-tertiary-fixed-variant": "#4b463c",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#584400",
        "on-background": "#1c1b1b",
        "surface": "#fcf9f8",
        "tertiary": "#2b271e",
        "inverse-on-surface": "#f3f0ef",
        "on-secondary": "#ffffff",
        "surface-container-high": "#eae7e7",
        "primary-container": "#800020",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0eded",
        "secondary-container": "#fccc38",
        "inverse-primary": "#ffb3b5",
        "tertiary-fixed-dim": "#cdc6b8",
        "surface-dim": "#dcd9d9",
        "inverse-surface": "#313030",
        "surface-container-lowest": "#ffffff",
        "background": "#fcf9f8",
        "on-tertiary-container": "#aea89a",
        "secondary-fixed-dim": "#f0c12c",
        "on-secondary-container": "#6f5600",
        "surface-variant": "#e5e2e1",
        "on-primary-fixed-variant": "#8e0f28",
        "on-primary-container": "#ff828a",
        "on-tertiary-fixed": "#1e1b13",
        "surface-container-low": "#f6f3f2",
        "primary-fixed": "#ffdada",
        "on-primary-fixed": "#40000b",
        "tertiary-fixed": "#e9e2d3",
        "surface-container-highest": "#e5e2e1",
        "primary": "#570013",
        "on-error-container": "#93000a",
        "surface-tint": "#af2b3e",
        "on-surface": "#1c1b1b",
        "secondary": "#755b00",
        "outline": "#8c7071",
        "surface-bright": "#fcf9f8",
        "primary-fixed-dim": "#ffb3b5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "base": "8px",
        "stack-md": "24px",
        "margin-mobile": "16px",
        "stack-sm": "12px",
        "margin-desktop": "64px",
        "stack-lg": "48px",
        "container-max": "1280px"
      },
      fontFamily: {
        "headline-md": ["Google Sans", "sans-serif"],
        "display-lg-mobile": ["Google Sans", "sans-serif"],
        "body-lg": ["Google Sans", "sans-serif"],
        "headline-md-mobile": ["Google Sans", "sans-serif"],
        "body-md": ["Google Sans", "sans-serif"],
        "display-lg": ["Google Sans", "sans-serif"],
        "title-lg": ["Google Sans", "sans-serif"],
        "label-md": ["Google Sans", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-lg": ["20px", { "lineHeight": "1.5", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
